title: Breathing Room
baseurl: /breathing_room
url: https://breathingroom-dot.github.io
theme: minima

# Simple Settings
description: a 20 something writing about politics and religion
author: Mary Szymanski

plugins:
  - jekyll-feed
  
